friendlyname = AudioWRT-%h
avfriendlyname = AudioWRT-%h

upnpav = 1
openhome = 0
lumincompat = 1
checkcontentformat = 1
enablel16 = false
saveohcredentials = 0

cachedir = /tmp/upmpdcli

mpdhost = 127.0.0.1
mpdport = 6600
ownqueue = 1
