#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only

START=90
USE_PROCD=1

start_service() {
	local enabled name backend device bitrate initial_volume log_stdout log_stderr

	config_load librespot
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0
	config_get name main name ''
	config_get backend main backend alsa
	config_get device main device default
	config_get bitrate main bitrate 160
	config_get initial_volume main initial_volume 50
	config_get_bool log_stdout main log_stdout 0
	config_get_bool log_stderr main log_stderr 1

	if [ -z "$name" ]; then
		name="$(uci -q get system.@system[0].hostname || echo OpenWrt)"
	fi

	procd_open_instance
	procd_set_param command /usr/bin/librespot
	procd_append_param command --name "$name"
	procd_append_param command --device-type speaker
	procd_append_param command --backend "$backend"
	procd_append_param command --device "$device"
	procd_append_param command --bitrate "$bitrate"
	procd_append_param command --initial-volume "$initial_volume"
	procd_append_param command --disable-audio-cache
	procd_set_param respawn
	procd_set_param stdout "$log_stdout"
	procd_set_param stderr "$log_stderr"
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger librespot
}
