'use strict';
'require view';
'require fs';
'require ui';
function parseStatus(text){var r={};(text||'').trim().split(/\n/).forEach(function(line){var p=line.indexOf('=');if(p>0)r[line.substring(0,p)]=line.substring(p+1);});return r;}
function formatKiB(value){var k=parseInt(value||'0',10);if(!k)return '-';if(k>=1048576)return(k/1048576).toFixed(1)+' GiB';return(k/1024).toFixed(1)+' MiB';}
return view.extend({
	load:function(){return Promise.all([L.resolveDefault(fs.exec('/usr/sbin/audiowrt-storage',['status']),{stdout:''}),L.resolveDefault(fs.exec('/usr/sbin/audiowrt-storage',['devices']),{stdout:''})]);},
	render:function(data){var status=parseStatus(data[0].stdout),self=this,devices=(data[1].stdout||'').trim().split(/\n/).filter(Boolean).map(function(line){var f=line.split('|');return{device:f[0],fstype:f[1]||'-',label:f[2]||'-',mounted:f[4]==='1'};});var rows=devices.length?devices.map(function(item){return E('div',{'class':'tr'},[E('div',{'class':'td left'},item.device),E('div',{'class':'td left'},item.fstype),E('div',{'class':'td left'},item.label),E('div',{'class':'td left'},item.mounted?_('Mounted'):E('button',{'class':'btn cbi-button-action','click':function(){self.enableStorage(item.device);}},_('Use for extensions')))]);}):[E('p',{},_('No unused USB storage partitions were detected.'))];return E('div',{'class':'cbi-map'},[E('h2',{},_('AudioWRT Storage')),E('div',{'class':'cbi-section'},[E('p',{},_('Internal flash keeps the AudioWRT core. Optional USB storage expands the writable OpenWrt overlay for larger audio extensions.')),E('p',{},[E('strong',{},_('Active storage: ')),status.active==='1'?_('External USB'):_('Internal flash')]),E('p',{},[E('strong',{},_('Root free space: ')),formatKiB(status.root_free_kb)]),status.active==='1'?E('button',{'class':'btn cbi-button-negative','click':function(){self.disableStorage();}},_('Return to internal storage')):'']),E('div',{'class':'cbi-section'},[E('h3',{},_('Available partitions')),E('p',{'class':'alert-message warning'},_('Preparing extension storage formats the selected partition as ext4 and permanently deletes all data on it.')),E('div',{'class':'table'},rows)])]);},
	enableStorage:function(device){if(!window.confirm(_('All data on %s will be erased. Continue?').format(device)))return;ui.showModal(_('Preparing extension storage'),[E('p',{'class':'spinning'},_('Formatting and copying the AudioWRT overlay...'))]);fs.exec('/usr/sbin/audiowrt-storage',['enable',device,'--yes']).then(function(res){ui.hideModal();if(res.code)throw new Error(res.stderr||_('Storage preparation failed.'));ui.addNotification(null,E('p',{},_('Storage is prepared. Reboot AudioWRT to activate it.')));}).catch(function(err){ui.hideModal();ui.addNotification(null,E('p',{},err.message||String(err)),'error');});},
	disableStorage:function(){if(!window.confirm(_('Return package storage to internal flash after the next reboot?')))return;fs.exec('/usr/sbin/audiowrt-storage',['disable','--yes']).then(function(res){if(res.code)throw new Error(res.stderr||_('Could not disable extension storage.'));ui.addNotification(null,E('p',{},_('External storage disabled. Reboot to use the internal core.')));}).catch(function(err){ui.addNotification(null,E('p',{},err.message||String(err)),'error');});},
	handleSaveApply:null,handleSave:null,handleReset:null
});
