music_directory "/mnt/music"
playlist_directory "/tmp/mpd/playlists"
state_file "/tmp/mpd/state"

bind_to_address "127.0.0.1"
port "6600"
restore_paused "yes"

audio_output {
	type "alsa"
	name "AudioWRT"
	device "default"
	mixer_type "software"
}
