music_directory "/mnt/music"
playlist_directory "/tmp/mpd/playlists"
db_file "/tmp/mpd/database"
state_file "/tmp/mpd/state"
sticker_file "/tmp/mpd/sticker.sql"

bind_to_address "0.0.0.0"
port "6600"

auto_update "yes"
restore_paused "yes"

audio_output {
	type "alsa"
	name "AudioWRT USB Audio"
	device "default"
	mixer_type "software"
}
