#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1
PROG=/usr/sbin/umdns

load_ifaces() {
	local network="$(uci -q get umdns.@umdns[-1].network)"
	for n in $network; do
		local device
		json_load "$(ifstatus $n)"
		json_get_var device l3_device
		[ -n "$device" ] && echo -n "$device "
	done
}

do_reload_service() {
	json_init
	json_add_array interfaces
	for i in $(load_ifaces); do
		json_add_string "" "$i"
	done
	json_close_array
	ubus call umdns set_config "$(json_dump)"
}

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	rc_procd start_service
	do_reload_service
}

service_running() {
	ubus -t 10 wait_for umdns && do_reload_service
}
