#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
	config_load audiowrt-dlna
	local enabled
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/libexec/audiowrt-dlna daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
