#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
set -eu
. /usr/libexec/audiowrt/config-save
[ "$#" -gt 0 ] || exit 0
[ $(( $# % 2 )) -eq 0 ] || exit 2
save_begin audiowrt-dlna
enabled=''
while [ "$#" -gt 0 ]; do
	key="$1"; value="$2"; shift 2
	case "$key" in
		enabled) case "$value" in 0|1) enabled=$value ;; *) exit 2 ;; esac ;;
		port) case "$value" in ''|*[!0-9]*) exit 2 ;; esac
			[ "$value" -ge 1024 ] && [ "$value" -le 65535 ] || exit 2 ;;
		volume) case "$value" in ''|*[!0-9]*) exit 2 ;; esac
			[ "$value" -le 100 ] || exit 2 ;;
		friendly_name|alsa_device) [ "${#value}" -le 200 ] || exit 2 ;;
		default_player_*)
			case "$key$value" in *[!a-zA-Z0-9_]*) exit 2 ;; esac ;;
		*) exit 2 ;;
	esac
	[ "$(printf '%s' "$value" | tr -d '\r\n')" = "$value" ] || exit 2
	if [ -n "$value" ]; then
		save_uci set "audiowrt-dlna.main.$key=$value"
	else
		save_uci delete "audiowrt-dlna.main.$key" || true
	fi
done
save_finish
case "$enabled" in
	0) /etc/init.d/audiowrt-renderer stop ;;
	1) /etc/init.d/audiowrt-renderer restart ;;
	*) /etc/init.d/audiowrt-renderer reload ;;
esac
